### PR TITLE
Added Word break problem of backtracking

### PR DESCRIPTION
**Pull request by SadafKausar2025**
@AkhzarFarhan  please merge this pr under hacktoberfest

### CODE REVIEW

**Review by AkhzarFarhan — APPROVED** [review]

**Comment by SadafKausar2025** [comment]
hello @AkhzarFarhan  please add hactoberfest accepted label in this

**Comment by AkhzarFarhan** [comment]
> @AkhzarFarhan  please merge this pr under hacktoberfest

Added, thanks for reminding 😊

**Comment by SadafKausar2025** [comment]
> > @AkhzarFarhan  please merge this pr under hacktoberfest
> 
> Added, thanks for reminding 😊

yaa , but this PR is not showing in my hactoberfest Profile
I think there is also need to add hactoberfest lable

**Comment by SadafKausar2025** [comment]
Screenshot (2510)

see this PR is having both label hactoberfest and also hactoberfest-accepted and also this is accepted by havtoberfest

**Comment by AkhzarFarhan** [comment]
Added labels ```hacktoberfest``` and ```hacktoberfest-accepted``` to all PRs, please check now @SadafKausar2025

**Pull request merged**
